# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
DISABLE_UPDATE_PROMPT=true

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="gentoo"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"
#unsetopt correct_all
#setopt correct

# Uncomment the following line to display red dots whilst waiting for completion.
#COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(gitfast scala sbt vagrant hub)

if [ -x /usr/libexec/path_helper ]; then
  eval `/usr/libexec/path_helper -s`
fi
source $ZSH/oh-my-zsh.sh

# User configuration

export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/nicholasisaacs/.rvm/bin":$PATH
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias c="clear"
alias src="source ~/.zshrc"
alias victory="cd ~/VictorOps"
alias cp-key="cat ~/.ssh/id_rsa.pub | pbcopy"
alias terminal.com="ssh -v root@niis00814.terminal.com"
alias start_kafka="/usr/local/Cellar/kafka/0.8.1.1/bin/kafka-server-start.sh /usr/local/etc/kafka/server.properties"
alias ports='sudo lsof -Pni | grep "LISTEN"'
alias slack="/Applications/Slack.app/Contents/MacOS/Slack &> /dev/null &"

# The Fuck
alias fuck='eval $(thefuck $(fc -ln -1 | tail -n 1)); fc -R'

# Hadoop
export HADOOP_PREFIX="/usr/local/Cellar/hadoop/2.5.0/libexec"
export HADOOP_CLASSPATH=$JAVA_HOME/lib/tools.jar
export JAVA_HOME=$(/usr/libexec/java_home)

# Mysql
export PATH="/usr/local/mysql-5.6.20-osx10.8-x86_64/bin":$PATH
export PATH="/Applications/Google\ Chrome.app/Contents/MacOS":$PATH

# Cassandra
export CQLSH_HOST="192.168.59.103"

# Docker
alias bootup="boot2docker up"
alias boot-restart="boot2docker restart"
export bootip="192.168.59.103"
export DOCKER_HOST="tcp://$bootip:2376"
export DOCKER_CERT_PATH=/Users/nicholasisaacs/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1
export NGROK_TOKEN="j8SaEtP8EG2HEQ0/J/Hg"
alias fig=docker-compose

# JDK Helpers
alias setJdk6='export JAVA_HOME=$(/usr/libexec/java_home -v 1.6)'
alias setJdk7='export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)'
alias setJdk8='export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)'


# Go
export GOPATH="/Users/nicholasisaacs/Go"

# Ruby pry
alias ruby='pry'
alias irb='pry'
alias yourKit='/Applications/YourKit_Java_Profiler_2014_build_14106.app/Contents/Resources/bin/yjp.sh'


# Node
export NPM_PACKAGES="${HOME}/.npm-packages"
export NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"
export PATH="$NPM_PACKAGES/bin:$PATH"

# Cabal
export PATH="/Users/nicholasisaacs/.cabal/bin:$PATH"

# VictorOps
function voKill() {
  ps aux|grep victorops|awk '{print $2}'|xargs sudo kill -9
}

# Git
function currentBranch() {
  git branch | grep "*" | awk '{print $2}'
}

function git_pretty_log () {
    hash="%C(yellow)%h%C(reset)"
    who="%C(white)%an%C(reset)"
    when="%C(white)%ar%C(reset)"
    refs="%C(blue)%d%C(reset)"
    what="%s%C(reset)"
    format="$hash $refs $what $who $when"
    git log --graph --color --abbrev-commit --date=relative --pretty="tformat:${format}" $* | sed -Ee 's/(seconds?|minutes?|hours?|days?|weeks?|months?|years?) ago/\1/' | sed -Ee 's/(years?), [[:digit:]]+ .*months?/\1/' | less -FXRS
}

# Last but not least, ASCII art
echo '
$$\   $$\ $$\           $$\                 $$$$$$\           $$\    $$\ $$\             $$\                          $$$$$$\
$$$\  $$ |\__|          $$ |              $$$ ___$$$\         $$ |   $$ |\__|            $$ |                        $$  __$$\
$$$$\ $$ |$$\  $$$$$$$\ $$ |  $$\        $$ _/   \_$$\        $$ |   $$ |$$\  $$$$$$$\ $$$$$$\    $$$$$$\   $$$$$$\  $$ /  $$ | $$$$$$\   $$$$$$$\
$$ $$\$$ |$$ |$$  _____|$$ | $$  |      $$ / $$$$$\ $$\       \$$\  $$  |$$ |$$  _____|\_$$  _|  $$  __$$\ $$  __$$\ $$ |  $$ |$$  __$$\ $$  _____|
$$ \$$$$ |$$ |$$ /      $$$$$$  /       $$ |$$  $$ |$$ |       \$$\$$  / $$ |$$ /        $$ |    $$ /  $$ |$$ |  \__|$$ |  $$ |$$ /  $$ |\$$$$$$\
$$ |\$$$ |$$ |$$ |      $$  _$$<        $$ |$$ /$$ |$$ |        \$$$  /  $$ |$$ |        $$ |$$\ $$ |  $$ |$$ |      $$ |  $$ |$$ |  $$ | \____$$\
$$ | \$$ |$$ |\$$$$$$$\ $$ | \$$\       $$ |\$$$$$$$$  |         \$  /   $$ |\$$$$$$$\   \$$$$  |\$$$$$$  |$$ |       $$$$$$  |$$$$$$$  |$$$$$$$  |
\__|  \__|\__| \_______|\__|  \__|      \$$\ \________/           \_/    \__| \_______|   \____/  \______/ \__|       \______/ $$  ____/ \_______/
                                         \$$$\   $$$\                                                                          $$ |
                                          \_$$$$$$  _|                                                                         $$ |
                                            \______/                                                                           \__|
'
export PATH=~/Tools/android/tools:$PATH

source /Users/nicholasisaacs/.iterm2_shell_integration.zsh
